---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Load FAS litters data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others

```{r}
select(litters_df, group, gd0_weight)
```


```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns...

```{r}
select(litters_df, GROUP = group, litter_number = litter_number)

rename(litters_df, GROUP = group, litter_number = litter_number)

```
?select_helpers

Select helpers

```{r}
select(litters_df, starts_with("gd"))

```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight <22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))

```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)

```

```{r}
filter(litters_df, group =="Mod8")
```


```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```


