---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

##Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

```

## Take a look at the data

Printing in the console.

```{r}
litters_df
```


```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

view(litters_df) in the console

##Options to read_csv

Check out ?read_csv to see more info
```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip=10, col_names=FALSE)
```

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
```

##Other file formats

Read in an excel file

```{r}
mlb_df = read_excel("./data/mlb11.xlsx")
```

Learn more at ?read_excel

Read in a sas file


```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
```


##Comparison with Base R

what about 'read.cvs' ...?

```{r}
litters_base = read.csv("./data/FAS_litters.csv")
litters_readr = read_csv("./data/FAS_litters.csv")

litters_base
litters_readr

```

##Exporting data

```{r}
mlb_df

write_csv(mlb_df, "./data/mlb_subtable.csv")
```

